name: Push Docker Image to Google Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/744564545457/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider-2"
          service_account: "github-actions@teak-store-433922-k0.iam.gserviceaccount.com"

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud --quiet auth configure-docker us-east5-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-east5-docker.pkg.dev/teak-store-433922-k0/cs-1660/image:latest .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push us-east5-docker.pkg.dev/teak-store-433922-k0/cs-1660/image:latest